name: CI Strategy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm api lint

  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm client lint

  typecheck-api:
    name: Typecheck API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: pnpm api typecheck

  typecheck-client:
    name: Typecheck Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: pnpm client typecheck

  vitest:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: vitest
        run: pnpm -r test

  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [lint-api, vitest, typecheck-client, typecheck-api, lint-client]
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd SkillCoop/
            ls
            echo "Stop all apps"
            pm2 stop all

            echo "Pulling latest code"
            git pull origin main

            echo "Install dependencies"
            pnpm Install

            echo "Build the project"
            pnpm schema build
            pnpm date build            
            pnpm types build
            pnpm api build 
            pnpm chat build

            echo "Database migration"
            pnpm api db:migrate:deploy

            echo "Start all apps"
            pm2 start skillcoop-pm2.json
      # sh deploy.sh

      #       cd SkillCoop/
      #       git fetch
      #       git pull origin main

      # - name: Checkout repo
      #   uses: actions/checkout@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      # - name: Install pnpm
      #   run: npm install -g pnpm

      # - name: Install dependencies with pnpm
      #   run: pnpm install

      # - name: Build API
      #   run: pnpm api build

      # - name: Build Chat
      #   run: pnpm chat build

      # - name: Database Migration
      #   run: pnpm api db:migrate:deploy

      # - name: Install pm2
      #   run: npm install pm2 -g

      # - name: Start apps
      #   run: pm2 restart all
